### ISSUE TITLE
Cost Routing Mistral/Llama2 cost research

### ISSUE THREAD

**Issue by TheVicBro** [llm-proxy/llm-proxy#96]
Creating framework to find Mistral/Llama2 cost
 - Aggregate a list of prompts to test (based on # of tokens)
 - Compare and contrast findings to external resources

**Comment by laxitshahi** [comment]
1. Create accounts for all of the different providers so that we can get a credit card from claudia (ENG 4000 helper)
2. Get all of the pricing data per some number of token: 0.05 / 1000 token; 5.0 / 1_000_000 tokens...
3. Document this data in a google sheets, or json; Google sheets may be easier, but json/yaml will be more programmatic
4. Standardize to per token or some other standard
5. replace all costs in each model with the respective values
6. test all models and ENSURE the routing makes sense

**Comment by laxitshahi** [comment]
We are using replicate for the cost per token price that hugging face does not give us.
https://replicate.com/pricing
